# This is a basic workflow to help you get started with Actions

name: Faze.Core.IO

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths: [ 'src/libraries/Faze.Core.IO/Faze.Core.IO/Faze.Core.IO.csproj' ]

env:
  SOLUTION_PATH: 'src/libraries/Faze.Core.IO'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
      
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: '5.0.x'
    - name: Install dependencies
      run: dotnet restore "${{ env.SOLUTION_PATH }}"
    - name: Build
      run: dotnet build "${{ env.SOLUTION_PATH }}" --configuration Release --no-restore
    - name: Test
      run: dotnet test "${{ env.SOLUTION_PATH }}" --no-restore --verbosity normal --collect:"XPlat Code Coverage" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=lcov
  
 
  publish-nuget:
    needs: build
  
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Publish NuGet
        # You may pin to the exact commit or the version.
        # uses: brandedoutcast/publish-nuget@c12b8546b67672ee38ac87bea491ac94a587f7cc
        uses: brandedoutcast/publish-nuget@v2.5.5
        with:
          # Filepath of the project to be packaged, relative to root of repository
          PROJECT_FILE_PATH: '${{ env.SOLUTION_PATH }}/Faze.Core.IO/Faze.Core.IO.csproj'
          NUGET_KEY: ${{secrets.NUGET_KEY}}
  
  publish-github:
    needs: build
  
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core @ Latest
      uses: actions/setup-dotnet@v1
      with:
        source-url: https://nuget.pkg.github.com/b-faze/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

    - name: Build solution and generate NuGet package
      run: dotnet build "${{ env.SOLUTION_PATH }}/Faze.Core.IO" -c Release

    - name: Push generated package to GitHub registry
      run: dotnet nuget push "${{ env.SOLUTION_PATH }}/Faze.Core.IO/bin/Release/*.nupkg" --skip-duplicate --no-symbols true
